// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWJwOeX4ANwPLAhC0075D8lNuahcijMo',
    appId: '1:833582821897:web:5a7b377bd7db22dc473ed8',
    messagingSenderId: '833582821897',
    projectId: 'impactly-284df',
    authDomain: 'impactly-284df.firebaseapp.com',
    storageBucket: 'impactly-284df.firebasestorage.app',
    measurementId: 'G-7L8PG46W9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXbS8BRWQkM9vdT4pLvBmoh_c6dHxepQ',
    appId: '1:833582821897:android:f00a7cf5166ab4c4473ed8',
    messagingSenderId: '833582821897',
    projectId: 'impactly-284df',
    storageBucket: 'impactly-284df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr3CWRxCzCYxktsu5I7yjETrTKtXr1K6o',
    appId: '1:833582821897:ios:7e1746c4d6ed50f8473ed8',
    messagingSenderId: '833582821897',
    projectId: 'impactly-284df',
    storageBucket: 'impactly-284df.firebasestorage.app',
    iosBundleId: 'com.example.impactlyNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr3CWRxCzCYxktsu5I7yjETrTKtXr1K6o',
    appId: '1:833582821897:ios:7e1746c4d6ed50f8473ed8',
    messagingSenderId: '833582821897',
    projectId: 'impactly-284df',
    storageBucket: 'impactly-284df.firebasestorage.app',
    iosBundleId: 'com.example.impactlyNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWJwOeX4ANwPLAhC0075D8lNuahcijMo',
    appId: '1:833582821897:web:f0857f8b428a53dc473ed8',
    messagingSenderId: '833582821897',
    projectId: 'impactly-284df',
    authDomain: 'impactly-284df.firebaseapp.com',
    storageBucket: 'impactly-284df.firebasestorage.app',
    measurementId: 'G-QDKD4PY7FH',
  );
}
